---
title: "Client Report - Project 0 - Introduction"
subtitle: "Course DS 250"
author: "Joshua Wiser"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
    
---

```{python}
# | label: libraries
# | include: false
import pandas as pd
import altair as alt
import numpy as np

from IPython.display import Markdown
from IPython.display import display
from tabulate import tabulate

```


## Elevator pitch

This project shows the relationship between the size of a cars engine and its fuel efficiency. Generally, the smaller the engine the more miles per gallon the car will get. There are some outliers, but this trend is easily visible.

```{python}
# | label: project data
# | code-summary: Read and format project data
# Include and execute your code here
url = (
    "https://github.com/byuidatascience/data4python4ds/raw/master/data-raw/mpg/mpg.csv"
)
mpg = pd.read_csv(url)
```

__Highlight the grand questions__

## GRAND QUESTION 1

MPG and Engine size

Engine size and miles per gallon have a direct correlation. In most cases, the smaller the engine, the more miles per gallon your car will get. There are some outliers where that may not always be true, but as a generalization you could say that smaller engine cars are better for fuel efficiency.

```{python}
# | label: GQ1
# | code-summary: Plot data
# Include and execute your code here
chart = alt.Chart(mpg).encode(x="displ", y="hwy").mark_circle()
chart


```

Most of these outliers are near the far right side of the graph, where a car with a larger engine may have better efficiency than those with small engines.




## GRAND QUESTION 2

Markdown table



```{python}
# | label: GQ2 chart
# | code-summary: table example
# | fig-cap: "My head table"
# | fig-align: center
# Include and execute your code here
print(
    mpg.head(5)
    .filter(["manufacturer", "model", "year", "hwy"])
    .to_markdown(index=False)
)
```






## APPENDIX A (Additional Python Code)

```python
#paste other your code from your python file (.py) here
```
